package cn.chace.www.springboot.mybatis.repository;

import cn.chace.www.springboot.mybatis.model.RuleDetail;
import java.util.List;

public interface RuleDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_detail
     *
     * @mbggenerated
     */
    int insert(RuleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_detail
     *
     * @mbggenerated
     */
    List<RuleDetail> selectAll();
}