package cn.chace.www.springboot.mybatis.model;

import cn.chace.www.springboot.mybatis.enums.DayOfWeek;

import java.sql.Time;

public class RuleDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_detail.ruleId
     *
     * @mbggenerated
     */
    private Integer ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_detail.dayOfWeek
     *
     * @mbggenerated
     */
    private DayOfWeek dayOfWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_detail.startTime
     *
     * @mbggenerated
     */
    private Time startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_detail.endTime
     *
     * @mbggenerated
     */
    private Time endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_detail.id
     *
     * @return the value of rule_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_detail.id
     *
     * @param id the value for rule_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_detail.ruleId
     *
     * @return the value of rule_detail.ruleId
     *
     * @mbggenerated
     */
    public Integer getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_detail.ruleId
     *
     * @param ruleId the value for rule_detail.ruleId
     *
     * @mbggenerated
     */
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }

    public DayOfWeek getDayOfWeek() {
        return dayOfWeek;
    }

    public void setDayOfWeek(DayOfWeek dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_detail.startTime
     *
     * @return the value of rule_detail.startTime
     *
     * @mbggenerated
     */
    public Time getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_detail.startTime
     *
     * @param startTime the value for rule_detail.startTime
     *
     * @mbggenerated
     */
    public void setStartTime(Time startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_detail.endTime
     *
     * @return the value of rule_detail.endTime
     *
     * @mbggenerated
     */
    public Time getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_detail.endTime
     *
     * @param endTime the value for rule_detail.endTime
     *
     * @mbggenerated
     */
    public void setEndTime(Time endTime) {
        this.endTime = endTime;
    }
}